name: build-deploy-pudl
on:
  workflow_dispatch:
  push:
    tags:
      - "v**"

jobs:
  print-env-vars:
    name: Print some envs vars
    runs-on: ubuntu-latest
    steps:
      - name: event_name
        run: echo ${{ github.event_name }}

      - name: GITHUB_REF
        run: echo ${{ env.GITHUB_REF }}
